### ISSUE TITLE
Keycloak test case doesn't work

### ISSUE THREAD

**Issue by eumel8** [codecentric/helm-charts#192]
chart version: 7.2.0
helm: v3.0.2
keycloak: 9.0.0

We tried the test functionality in Keycloak with Selenium POD but that ended permanently in error state: 

```
 helm test keycloak -n keycloak
```

Logs

```
$ kubectl logs keycloak-test-q4uj5 -n keycloak
Creating PhantomJS driver...
Opening Keycloak...
Entering username...
Entering password...
Clicking login button...
Traceback (most recent call last):
  File "/tests/test.py", line 30, in <module>
    login_button.click()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: {"errorMessage":"Element does not exist in cache","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"81","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:56473","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"id\": \":wdc:1584097862437\", \"sessionId\": \"532b7220-651b-11ea-86cc-77bf8cd5a37e\"}","url":"/click","urlParsed":{"anchor":"","query":"","file":"click","directory":"/","path":"/click","relative":"/click","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/click","queryKey":{},"chunks":["click"]},"urlOriginal":"/session/532b7220-651b-11ea-86cc-77bf8cd5a37e/element/:wdc:1584097862437/click"}}
Screenshot: available via screen
```

Log data are correct,. It seems I've got a session id but Python is not able to click the login button. Keycloak is roll out of the box with the default schema.

**Comment by unguiculus** [comment]
The chart has not yet been updated for 9.0.0. There may have been changes that cause this problem.

**Comment by unguiculus** [comment]
Closing as outdated.
