### ISSUE TITLE
Keycloak - Can't get vault for LDAP bindCredential to work with Kubernetes secret 

### ISSUE THREAD

**Issue by nicolas-guerrier** [codecentric/helm-charts#241]
Hello,

I am trying to use vault (see https://www.keycloak.org/docs/latest/server_admin/#_vault-administration) to populate LDAP bind credentials, but no success til now.

Any advice?

### 0. Softwares

- Ubuntu 18.04 (tested against 20.04 too)
- k3s version v1.18.4+k3s1 (97b7a0e9)
- Longhorn v1.0.0
- helm v3.2.4
- osixia/openldap

### 1. Steps

- Created namespace
`kubectl create namespace auth`
- Created secret for realm.json (exported from a previous test install of keycloak, and edited to specify ldap info (connectionUrl for ldap ip & bindCredential using vault)
`kubectl create secret generic realm --from-file=./realm.json -n auth`
- Created secret for bindCredential
`kubectl create secret generic ldapbindcredentials --from-file=./realmname_ldapbindcredentials -n auth`
- Downloaded values.yaml file from repo and updated next values : 
```
keycloak:
  basepath: ""
  extraArgs: -Dkeycloak.import=/realm/realm.json
  extraVolumes: |
    - name: realm
      secret:
        secretName: realm
    - name: ldapbindcredentials
      secret:
        secretName: ldapbindcredentials
  extraVolumeMounts: |
    - name: realm
      mountPath: "/realm/"
      readOnly: true
    - name: ldapbindcredentials
      mountPath: "/opt/jboss/keycloak/secrets/"
      readOnly: true
  persistence:
    deployPostgres: true
    dbVendor: postgres
postgresql:
  persistence:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
```
- Installed Keycloak using helm chart in previously created namespace
`helm install keycloak codecentric/keycloak -n auth -f values.yaml`

### 2. Result

- Keycloak successfully installed, and realm successfully imported
- During installation, saw next logs : 
```
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0
** Adding vault spi **
{"outcome" => "success"}
{"outcome" => "success"}
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0
** Adding vault spi **
{"outcome" => "success"}
{"outcome" => "success"}
```
- Ldap connection tested : ok (from realm federation settings)
![image](https://user-images.githubusercontent.com/10116825/85213587-ab46d600-b360-11ea-8c90-26d13ad57450.png)
![image](https://user-images.githubusercontent.com/10116825/85213596-da5d4780-b360-11ea-99dc-3cab3eac6942.png)
- Ldap authentication using vault : not ok
![image](https://user-images.githubusercontent.com/10116825/85213592-d03b4900-b360-11ea-9bb5-dabc49f70217.png)
![image](https://user-images.githubusercontent.com/10116825/85213599-e21cec00-b360-11ea-80cf-baa7b816fef0.png)
- Ldap authentication using password : ok
![image](https://user-images.githubusercontent.com/10116825/85213613-08428c00-b361-11ea-8bf7-5a5368a6bc56.png)
![image](https://user-images.githubusercontent.com/10116825/85213616-11335d80-b361-11ea-8a47-edd25240643e.png)
- Logs when failed auth (with vault)
```
kubectl logs keycloak-0 -n auth
23:48:21,915 ERROR [org.keycloak.services] (default task-7) KC-SERVICES0055: Error when authenticating to LDAP: [LDAP: error code 49 - Invalid Credentials]: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
	at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3158)
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3104)
	at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2890)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2804)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:320)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at org.jboss.as.naming@19.0.0.Final//org.jboss.as.naming.InitialContext.getDefaultInitCtx(InitialContext.java:116)
	at org.jboss.as.naming@19.0.0.Final//org.jboss.as.naming.InitialContext.init(InitialContext.java:101)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.jboss.as.naming@19.0.0.Final//org.jboss.as.naming.InitialContext.<init>(InitialContext.java:91)
	at org.jboss.as.naming@19.0.0.Final//org.jboss.as.naming.InitialContextFactory.getInitialContext(InitialContextFactory.java:43)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:719)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.keycloak-ldap-federation@10.0.0//org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:77)
	at org.keycloak.keycloak-ldap-federation@10.0.0//org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:91)
	at org.keycloak.keycloak-services@10.0.0//org.keycloak.services.managers.LDAPConnectionTestManager.testLDAP(LDAPConnectionTestManager.java:76)
	at org.keycloak.keycloak-services@10.0.0//org.keycloak.services.resources.admin.RealmAdminResource.testLDAPConnection(RealmAdminResource.java:945)
	at org.keycloak.keycloak-services@10.0.0//org.keycloak.services.resources.admin.RealmAdminResource.testLDAPConnection(RealmAdminResource.java:958)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:526)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:376)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:347)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.resteasy-jaxrs@3.11.0.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.keycloak-services@10.0.0//org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:91)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.30.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.30.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.30.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.0.30.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.30.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.30.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.30.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.30.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.30.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at org.wildfly.extension.undertow@19.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.30.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.0.30.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.core@2.0.30.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
- From container, secret / vault looks like : 
```kubectl exec -it keycloak-0 -n auth bash

bash-4.4$ ls -l /opt/jboss/keycloak/
total 532
drwxrwx--x 1 jboss root   4096 Jun 20 23:14 bin
drwxrwxr-x 7 jboss root   4096 Apr 30 12:42 docs
drwxrwx--x 5 jboss root   4096 Apr 29 07:29 domain
-rw-rw-r-- 1 jboss root 488837 Apr 29 07:27 jboss-modules.jar
-rw-rw-r-- 1 jboss root  11358 Apr 29 07:29 LICENSE.txt
drwxrwxr-x 3 jboss root   4096 Apr 30 12:42 modules
drwxrwsrwt 3 root  1000    100 Jun 20 23:12 secrets
drwxrwx--x 1 jboss root   4096 Apr 30 12:42 standalone
drwxrwxr-x 5 jboss root   4096 Apr 30 12:41 themes
-rw-rw-r-- 1 jboss root     26 Jan 30 13:50 version.txt
drwxrwxr-x 2 jboss root   4096 Apr 30 12:42 welcome-content

bash-4.4$ ls -l /opt/jboss/keycloak/secrets/
total 0
lrwxrwxrwx 1 root root 36 Jun 20 23:12 realmname_ldapbindcredentials -> ..data/realmname_ldapbindcredentials

bash-4.4$ cat /opt/jboss/keycloak/secrets/realmname_ldapbindcredentials 
test
```

Sorry for long post, but kinda getting crazy here ;) If anyone has some experience using Kubernetes secrets as Keycloak vault, help would be appreciated :) 

I may help with chart / image documentation once I get this to work! ;)

Thx!

**Comment by micedre** [comment]
In case you didn't manage to find a solution, or if somebody else stumble upon it, this is a bug int he keycloak container image (https://issues.redhat.com/browse/KEYCLOAK-15899)

I think getting the 11.0.3 version of the image should work better. 

But you can also add a startup scripts like this : 

```
startupScripts:
    # WildFly CLI script for configuring the node-identifier
    keycloak.cli: |
        embed-server --server-config=standalone-ha.xml --std-out=echo
        batch

        echo Configuring node identifier
        ## Sets the node identifier to the node name (= pod name). Node identifiers have to be unique. They can have a
        ## maximum length of 23 characters. Thus, the chart's fullname template truncates its length accordingly.
        /subsystem=transactions:write-attribute(name=node-identifier, value=${jboss.node.name})
        /subsystem=keycloak-server/spi=vault/:add
        /subsystem=keycloak-server/spi=vault/provider=files-plaintext/:add(enabled=true,properties={dir => "/opt/jboss/keycloak/secrets/"})
        /subsystem=keycloak-server/spi=vault:write-attribute(name=default-provider,value=files-plaintext)
        echo Finished configuring node identifier

        run-batch
        stop-embedded-server
```
