### ISSUE TITLE
failed to resolve interface private

### ISSUE THREAD

**Issue by krakazyabra** [codecentric/helm-charts#415]
Hello. I've daced with problem, running this chart.
Set my extraEnv
```yaml
      extraEnv:
          - name: 'DB_VENDOR'
            value: 'postgres'
          - name: 'DB_ADDR'
            value: 'keycloak-stolon-proxy'
          - name: 'DB_PORT'
            value: '5432'
          - name: 'DB_DATABASE'
            value: 'keycloak'
          - name: 'DB_USER'
            value: 'keycloak'
          - name: 'DB_PASSWORD'
            value: 'password'
          - name: 'KEYCLOAK_USER'
            value: 'admin'
          - name: 'KEYCLOAK_PASSWORD'
            value: 'password'
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: dns.DNS_PING
          - name: JGROUPS_DISCOVERY_PROPERTIES
            value: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: CACHE_OWNERS_COUNT
            value: "2"
          - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
            value: "2"
          - name: JAVA_OPTS
            value: >-
              -Djboss.bind.address.private=127.0.0.1
              -Djboss.bind.address=0.0.0.0
              -Djava.net.preferIPv4Stack=true
              -Djboss.bind.address.unsecure=127.0.0.1
```

During launching the pod I see such errors:
```shell
10:55:05,280 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service org.wildfly.network.interface.private: org.jboss.msc.service.StartException in service org.wildfly.network.interface.private: WFLYSRV0082: failed to resolve interface private
        at org.jboss.as.server@10.0.3.Final//org.jboss.as.server.services.net.NetworkInterfaceService.start(NetworkInterfaceService.java:96)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
        at java.base/java.lang.Thread.run(Thread.java:834)
10:55:05,416 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("interface" => "private")]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.network.interface.private" => "WFLYSRV0082: failed to resolve interface private"}}
10:55:06,148 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
10:55:06,155 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.network.interface.private: WFLYSRV0082: failed to resolve interface private
WFLYCTL0448: 46 additional services are down due to their dependencies being missing or failed
10:55:06,418 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
10:55:06,446 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
10:55:06,447 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
10:55:06,447 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: Keycloak 9.0.0 (WildFly Core 10.0.3.Final) started (with errors) in 22686ms - Started 479 of 941 services (53 services failed or missing dependencies, 698 services are lazy, passive or on-demand)
```

I would be grateful for any help.

**Comment by thomasdarimont** [comment]
@krakazyabra on which platform do you run your Keycloak pods?

**Comment by krakazyabra** [comment]
Hello, we're running it on kubernetes 1.20.5. keycloak image is from original dockerhub repo.

**Comment by juliohm1978** [comment]
I'm having the exact same issue. I suspect that it started when I enabled IPv6, turning my cluster into a dual stack.

I'm not sure what other options I can include in JAVA_OPTS to fix this. Help is appreciated. Thanks.

Current values:
```yaml
        extraEnv: |
          - name: JAVA_OPTS
            value: >-
              -XX:MaxRAMPercentage=90
              -Djava.net.preferIPv4Stack=true
              -Djboss.bind.address.private=127.0.0.1
              -Djboss.bind.address.management=0.0.0.0
              -Djboss.bind.address=0.0.0.0
```

**Comment by juliohm1978** [comment]
Follow up...

If you k8s cluster is IPv6 only or dual stack, you can work around this by using

```yaml
        extraEnv: |
          - name: JAVA_OPTS
            value: >-
              -Djava.net.preferIPv4Stack=false
              -Djava.net.preferIPv6Addresses=true
              -Djboss.bind.address.private=::1
              -Djboss.bind.address.management=::
              -Djboss.bind.address=::
```

That allows keycloak to startup, but with the following error:

```
15:53:03,965 ERROR [org.jboss.modcluster] (ServerService Thread Pool -- 58) MODCLUSTER000034: Failed to start advertise listener: java.net.SocketException: bad argument for IP_MULTICAST_IF: address not bound to any interface
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:91)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:352)
	at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:477)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.init(AdvertiseListenerImpl.java:151)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.start(AdvertiseListenerImpl.java:161)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.ModClusterService.init(ModClusterService.java:166)
	at org.wildfly.mod_cluster.undertow@23.0.2.Final//org.wildfly.mod_cluster.undertow.UndertowEventHandlerAdapterService.start(UndertowEventHandlerAdapterService.java:83)
	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

Adding `-Djboss.bind.address.unsecure=::` makes no difference.

While Keycloak can now start up and respond, I am not sure how this error affects its ability to be part of a cluster with multiple instances.

**Comment by subodhcjoshi82** [comment]
I am getting the above error and Keycloak is telling in logs it's started but POD is not coming up.
