### ISSUE TITLE
Unable to read rebalancing status from coordinator keycloak-0

### ISSUE THREAD

**Issue by gurwns1540** [codecentric/helm-charts#441]
i can't resolve this problem

`02:02:01,560 INFO  [org.infinispan.PERSISTENCE] (MSC service thread 1-1) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.marshalling.jboss.JBossMarshaller'
02:02:01,562 INFO  [org.infinispan.PERSISTENCE] (MSC service thread 1-2) ISPN000556: Starting user marshaller 'org.wildfly.clustering.infinispan.marshalling.jboss.JBossMarshaller'
02:02:01,583 INFO  [org.infinispan.CONTAINER] (MSC service thread 1-1) ISPN000128: Infinispan version: Infinispan 'Turia' 10.1.8.Final
02:02:01,727 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-1) ISPN000078: Starting JGroups channel ejb
02:02:01,727 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-2) ISPN000078: Starting JGroups channel ejb
02:02:01,732 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [keycloak-0|61] (2) [keycloak-0, keycloak-test-0]
02:02:01,733 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [keycloak-0|61] (2) [keycloak-0, keycloak-test-0]
02:02:01,745 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-2) ISPN000079: Channel ejb local address is keycloak-test-0, physical addresses are [10.244.1.70:55200]
02:02:01,753 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-1) ISPN000079: Channel ejb local address is keycloak-test-0, physical addresses are [10.244.1.70:55200]
02:02:01,782 WARN  [org.infinispan.topology.ClusterTopologyManagerImpl] (MSC service thread 1-1) ISPN000329: Unable to read rebalancing status from coordinator keycloak-0: java.util.concurrent.CompletionException: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-0, see cause for remote stack trace
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
        at org.infinispan@10.1.8.Final//org.infinispan.topology.TopologyManagementHelper.executeOnCoordinator(TopologyManagementHelper.java:102)
        at org.infinispan@10.1.8.Final//org.infinispan.topology.ClusterTopologyManagerImpl.fetchRebalancingStatusFromCoordinator(ClusterTopologyManagerImpl.java:160)
        at org.infinispan@10.1.8.Final//org.infinispan.topology.ClusterTopologyManagerImpl.start(ClusterTopologyManagerImpl.java:149)
        at org.infinispan@10.1.8.Final//org.infinispan.topology.CorePackageImpl$4.start(CorePackageImpl.java:87)
        at org.infinispan@10.1.8.Final//org.infinispan.topology.CorePackageImpl$4.start(CorePackageImpl.java:71)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:587)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:578)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:605)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:569)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:547)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:770)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:341)
        at org.infinispan@10.1.8.Final//org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:237)
        at org.infinispan@10.1.8.Final//org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:755)
        at org.infinispan@10.1.8.Final//org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:726)
        at org.jboss.as.clustering.infinispan@20.0.1.Final//org.jboss.as.clustering.infinispan.subsystem.CacheContainerServiceConfigurator.get(CacheContainerServiceConfigurator.java:120)
        at org.jboss.as.clustering.infinispan@20.0.1.Final//org.jboss.as.clustering.infinispan.subsystem.CacheContainerServiceConfigurator.get(CacheContainerServiceConfigurator.java:74)
        at org.wildfly.clustering.service@20.0.1.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-0, see cause for remote stack trace
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.ResponseCollectors.wrapRemoteException(ResponseCollectors.java:25)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.withException(ValidSingleResponseCollector.java:37)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.ValidSingleResponseCollector.addResponse(ValidSingleResponseCollector.java:21)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.addResponse(SingleTargetRequest.java:72)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.impl.SingleTargetRequest.onResponse(SingleTargetRequest.java:42)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.impl.RequestRepository.addResponse(RequestRepository.java:52)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1435)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1338)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:132)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1487)
        at org.jgroups@4.2.4.Final//org.jgroups.JChannel.up(JChannel.java:784)
        at org.jgroups@4.2.4.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
        at org.jgroups@4.2.4.Final//org.jgroups.stack.Protocol.up(Protocol.java:306)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:343)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:343)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:868)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:243)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1049)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:772)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:753)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
        at org.jgroups@4.2.4.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1385)
        at org.jgroups@4.2.4.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.jboss.as.clustering.common@20.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
        at org.jboss.as.clustering.common@20.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
        ... 1 more
Caused by: org.infinispan.commons.CacheException: Unknown command id 17!
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:181)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.exts.ThrowableExternalizer.readObject(ThrowableExternalizer.java:42)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:728)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:709)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:358)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:49)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.responses.ExceptionResponse$Externalizer.readObject(ExceptionResponse.java:41)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:728)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:709)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:358)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:192)
        at org.infinispan@10.1.8.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:221)
        at org.infinispan@10.1.8.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1427)
        ... 29 more
`

**Comment by masinger** [comment]
We are currently observing the same situation on a fresh install.

**Comment by masinger** [comment]
**Solution** (at least for us)
In case someone comes back to this issue. Our problem has been caused by multiple Keycloaks running within the same Kubernetes cluster, causing the `JGROUP_DISCOVERY` to detect unrelated Keycloak instances. We have been able to fix it by using the DNS discovery strategy.

```yaml
extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: dns.DNS_PING
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: 'dns_query={{ include "keycloak.serviceDnsName" . }}'
```
