### ISSUE TITLE
Keycloak unable to connect to mysql

### ISSUE THREAD

**Issue by algakzru** [codecentric/helm-charts#49]
When I try to set keycloak persistence to mysql it throws UnknownHostException :

```
Caused by: java.net.UnknownHostException: mysql: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:301)
	... 68 more
```

Other pods in my cluster have no problem connecting to mysql service, only keycloak pod has this issue.

## How to reproduce:

Install mysql
```
helm install --name mysql --set imageTag=5.6,mysqlRootPassword=secretpassword,mysqlUser=keycloak,mysqlPassword=password,mysqlDatabase=keycloak stable/mysql
```

Install keycloak
```
helm install --name keycloak --set keycloak.username=admin,keycloak.password=admin,keycloak.persistence.deployPostgres=false,keycloak.persistence.dbVendor=mysql,keycloak.persistence.dbName=keycloak,keycloak.persistence.dbHost=mysql,keycloak.persistence.dbPort=3306,keycloak.persistence.dbUser=keycloak,keycloak.persistence.dbPassword=password codecentric/keycloak
```

## Environment:

Linux version: CentOS Linux 7 (Core)
Kubernetes version: v1.14.2
Network: flannel:v0.11.0-amd64

**Comment by algakzru** [comment]
After troubleshooting I realized a node where keycloak pod was running had some network issues, after restarting the node keycloak was able to connect to mysql. So nothing wrong with keycloak, I am closing this issue.
