### ISSUE TITLE
LDAPS failed betwenn Keycloak and Freeipa - CA certificate not found 

### ISSUE THREAD

**Issue by wilf1rst** [codecentric/helm-charts#99]
Hello,

I use the helm charts available in this repository to install keycloak on my kubernetes cluster.
When I want to add my freeipa implementation as User federation source using LDAPS connection between Keycloak and Freeipa I encounter an error.

The connection test works but the authentication test failed with this eror:
```
21:23:14,482 ERROR [org.keycloak.services] (default task-47) KC-SERVICES0055: Error when authenticating to LDAP: simple bind failed: myfreeipa.fqdn:636: javax.naming.CommunicationException: simple bind failed: myfreeipa.fqdn:636 [Root exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2791)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at org.jboss.as.naming.InitialContext.getDefaultInitCtx(InitialContext.java:116)
	at org.jboss.as.naming.InitialContext.init(InitialContext.java:101)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.jboss.as.naming.InitialContext.<init>(InitialContext.java:91)
	at org.jboss.as.naming.InitialContextFactory.getInitialContext(InitialContextFactory.java:43)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.keycloak.services.managers.LDAPConnectionTestManager.testLDAP(LDAPConnectionTestManager.java:77)
	at org.keycloak.services.resources.admin.RealmAdminResource.testLDAPConnection(RealmAdminResource.java:940)
	at sun.reflect.GeneratedMethodAccessor724.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:366)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:137)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.sun.jndi.ldap.Connection.writeRequest(Connection.java:443)
	at com.sun.jndi.ldap.Connection.writeRequest(Connection.java:416)
	at com.sun.jndi.ldap.LdapClient.ldapBind(LdapClient.java:359)
	at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:214)
	... 87 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 100 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 106 more
```
I assume it's a certifcate issue as my main Freeipa ca certificate is not know by keycloak to make the ldaps query authentication.

For example in my kubernetes / rancher cluster I've to add the certificate to rancher to be able to make a ldaps call and authenticate against my freeipa server.

A few search on the internet show that I can import certificate in the keystore using the keytool utility. As here the deployment use helm chart do you have a clue how to import my ca certificate inside the keycloak deployment ?

**Comment by unguiculus** [comment]
Check out this example for our Jenkins chart. You should be able to adapt it and achieve something similar for Keycloak:

https://github.com/codecentric/helm-charts/tree/master/charts/jenkins#updating-javas-truststore

**Comment by wilf1rst** [comment]
Hello @unguiculus,
I check your documentation but i struggle to reproduce the same for keycloak.

Here's what i tried.
I create a config map that contain my `ldap-ca.crt`:
``` 
kubectl -n keycloak create configmap ldap-ca-configmap --from-file=ldap-ca.crt --dry-run --output yaml | kubectl apply -f -
```
Download your helm charts and modifying the values.yaml to add the following:
```
referenceContent:
  - relativeDir: custom-init-scripts
    defaultMode: 0555
    data:
      - fileName: truststore.sh
        fileContent: |
          #!/usr/bin/env bash

          echo 'Adding CA certificate to Java truststore...'
          cd /opt/jboss/keycloak/standalone/configuration/keystores 
          chmod 666 /opt/jboss/keycloak/standalone/configuration/keystores 
          keytool -keystore truststore -storepass [a stong password] -noprompt -trustcacerts -importcert -alias ldap-ca -file ./ldap-ca/ldap-ca.crt
          chmod 444 /opt/jboss/keycloak/standalone/configuration/keystores 

  ## Additional init containers, e. g. for providing custom themes
  extraInitContainers: |
    - name: keycloak-truststore-init
      image: jboss/keycloak
      tag: 6.0.1
      imagePullPolicy: IfNotPresent
      command:
        - /opt/jboss/keycloak/custom-init-scripts/truststore.sh
      volumeMounts:
        - name: ldap-ca
          mountPath: /opt/jboss/keycloak/standalone/configuration/keystores/ldap-ca
        - name: truststore
          mountPath: /opt/jboss/keycloak/standalone/configuration/keystores 

 extraVolumes: |
    - name: ldap-ca
      configMap:
        name: ldap-ca-configmap
    - name: truststore
      emptyDir: {}

 extraVolumeMounts: |
    - name: truststore
      mountPath: /opt/jboss/keycloak/standalone/configuration/keystores 

javaOpts: >-
    -Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/keystores/truststore
```

One of the problem I encounter is this one when I lauch the helm charts with the modified values:
```
Error: failed to start container "keycloak-truststore-init": Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/opt/jboss/keycloak/custom-init-scripts/truststore.sh\": stat /opt/jboss/keycloak/custom-init-scripts/truststore.sh: no such file or directory": unknown
```
I think it's because I didn't have persistence on the keycloak pod itself and I've to set a pvc to be able to mount the volume as `keycloak_home` in the `extraInitContainers` to be able to perform the operation. Also I have to modify the statefulset templates to mount the volume `keycloak_home` on the keycloak containers.

What do you think ?

**Comment by vishalreddy277** [comment]
@wilf1rst did you find out a solution for this ? even i am stuck in the same issue regarding certs

**Comment by unguiculus** [comment]
The chart supports custom startup scripts. The following should be possible:

```yaml
keycloak:
  startupScripts:
    truststore.sh: |
      #!/usr/bin/env bash

      echo 'Adding CA certificate to Java truststore...'
      cd /opt/jboss/keycloak/standalone/configuration/keystores 
      chmod 666 /opt/jboss/keycloak/standalone/configuration/keystores 
      keytool -keystore truststore -storepass [a stong password] -noprompt -trustcacerts -importcert -alias ldap-ca -file ./ldap-ca/ldap-ca.crt
      chmod 444 /opt/jboss/keycloak/standalone/configuration/keystores 
```

**Comment by mikemowgli** [comment]
@unguiculus , this is an interesting proposal, though I wonder two things:
1. how can the Helm values file pass the content of the file to add? Your above script mentions `-file ./ldap-ca/ldap-ca.crt` but the file needs to be exposed to the running container...
2. where is it configured that anything in /opt/jboss/keycloak/standalone/configuration/keystores will be taken into account by Keycloak? As [the official doc states|https://www.keycloak.org/docs/latest/server_installation/index.html#_truststore] that a trust store should be configured with a `<spi name="truststore">` block, and there is none of it in standalone.xml.
3. Assuming anything in that subdirectory will indeed be treated as additional keystores by Keycloak, how will it guess `[a stong password]` defined in your above script?

**Comment by mikemowgli** [comment]
I finally managed to get my customs certificates trusted with a combination of the X509_CA_BUNDLE variable (used in this script: `/opt/jboss/tools/x509.sh`) and an extra init container that copies the certificates in an extra volume.

Warnings:
- there's a bug in keycloak docker image v7.0.0 in the `/opt/jboss/tools/x509.sh` script that is fixed in v8.0.1. Make sur to use that one.
- make sure to explicitly define the PROXY_ADDRESS_FORWARDING variable since the usage of any other variable in `extraEnv` will undefine the default value for `extraEnv`.
```
extraEnv: |
    - name: X509_CA_BUNDLE
      value: "/tmp/certs/*.crt"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  extraInitContainers: |
    - name: isabel-certs
      image: my.private.registry/certs
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying certificates..."
          cp -r /certs/* /tmp/certs
      volumeMounts:
        - name: certs
          mountPath: /tmp/certs
  extraVolumeMounts: |
    - name: certs
      mountPath: /tmp/certs
  extraVolumes: |
    - name: certs
      emptyDir: {}
```

Here's my Dockerfile for the init container:
```
FROM busybox

COPY certs/ /certs/
```

**Comment by rdcarrera** [comment]
Hi, I created a container with an easy way to solve this, I copied the idea from: https://github.com/codecentric/helm-charts/tree/master/charts/jenkins#updating-javas-truststore, 

https://github.com/rdcarrera/add-ca-to-cacert

First you must created a configmap with the certificate:
```
---
kind: ConfigMap
metadata:
  name: a-ca-certificate
data:
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
    fooooooo
    ......
    fooooooo
    -----END CERTIFICATE-----
```
And then add to your helm variables files: 

```
---
keycloak:
 extraInitContainers: |
    - name: "trust-ca-certificate"
      image: "rdcarrera/add-ca-to-cacert"
      imagePullPolicy: Always
      env:
      - name: CACERT_DEST
        value: "/test"
      volumeMounts:
      - name: cacerts-binary
        mountPath: /test
      - name: a-ca-certificate
        mountPath: /certs/ca.pem
        subPath: ca.pem

  extraVolumeMounts: |
    - name: cacerts-binary
      mountPath: /etc/pki/ca-trust/extracted/java/cacerts
      subPath: cacerts
      readOnly: true

  extraVolumes: |
    - name: a-ca-certificate
      configMap:
        name: a-ca-certificate
    - name: cacerts-binary
      emptyDir: {}
```

Also, Give thanks to @unguiculus . 

Regards.

**Comment by bbfeng1979** [comment]
在KeyCloak的镜像中提供加载外部证书的功能，可以参考 https://hub.docker.com/r/jboss/keycloak 中 Setting up TLS(SSL) 部分，这里的解决方法如下，先自己生成一个包含所有证书的 ConfigMap，然后在 Values 中添加下面的设置，其中 keycloak-outgoing-ca 是自己的 CM：
```
    extraEnv: |
     - name: X509_CA_BUNDLE
       value: "/tmp/certs/*.crt"
    extraVolumeMounts: |
      - name: keycloak-outgoing-ca
        mountPath: /tmp/certs
    extraVolumes: |
      - name: keycloak-outgoing-ca
        configMap:
          name: keycloak-outgoing-ca
```

**Comment by tkg61** [comment]
> 在KeyCloak的镜像中提供加载外部证书的功能，可以参考 https://hub.docker.com/r/jboss/keycloak 中 Setting up TLS(SSL) 部分，这里的解决方法如下，先自己生成一个包含所有证书的 ConfigMap，然后在 Values 中添加下面的设置，其中 keycloak-outgoing-ca 是自己的 CM：
> 
> ```
>     extraEnv: |
>      - name: X509_CA_BUNDLE
>        value: "/tmp/certs/*.crt"
>     extraVolumeMounts: |
>       - name: keycloak-outgoing-ca
>         mountPath: /tmp/certs
>     extraVolumes: |
>       - name: keycloak-outgoing-ca
>         configMap:
>           name: keycloak-outgoing-ca
> ```
> 
> 完事以后，配置下 Realm 中的 Email，添加一个带 SSL 的邮箱，然后开启 Login 的忘记密码功能，然后试试能否通过邮箱找回密码，其它类似需要增加外部证书的情况，直接修改 keycloak-outgoing-ca 增加证书即可。

Thanks for this! This solution solved my issue in running the latest version (9.0) inside of a Kubernetes cluster running on a postgres db and using Helm to deploy. 

I created my own values.yaml config, added these in under the keycloak section and had a config map made already to hold my cert (key was ca.crt and value was the plain text of the cert, not b64 encoded)

Hope it helps someone else out!

**Comment by ognjen-it** [comment]
Hello Allo,

I have had the same issue as you and couldn't resolve it with the messages above. So, I will try to explain to all people who want to resolve it as simply as possible.

- Step 1
You need to have the CA certificate of LDAPS. Then run the next command to add this CA certificate to the truststure.jks:
`keytool -import -alias youre.ldaps.domain.com -keystore truststore.jks -file ca.crt`
**You will be asked to create the password. This password need to be in the file keycloak-values.yml which you will create in the Step 3**

- Step 2
After that, you will see `truststore.jks` in the current directory. Next, need to add to the Kubernetes secret:
`kubectl create secret generic ldap-keystore --from-file=truststore.jks`

- Step 3
Then create the file keycloak-values.yml with next information. Just need to change LDAPS_TRUSTSTORE_PASSWORD to your password that you created in Step 1.
```
extraEnv: |
  - name: KEYCLOAK_USER
    value: AdminUser
  - name: KEYCLOAK_PASSWORD
    value: AdminPassword
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
      -Djavax.net.ssl.trustStore=/opt/jboss/.cacerts/truststore.jks
      -Djavax.net.ssl.trustStorePassword=LDAPS_TRUSTSTORE_PASSWORD
extraVolumes: |
  - name: scert
    secret:
      secretName: ldap-keystore
extraVolumeMounts: |
  - name: scert
    mountPath: /opt/jboss/.cacerts
    readOnly: true
```

- Step 4
You can deploy your keycloak trough HELM!
`helm install keycloak codecentric/keycloak -f keycloak-values.yml`

**Happy helming!** :)
